# Generated by Django 4.1.3 on 2022-11-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croppingApp', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
