# Generated by Django 4.1.3 on 2022-11-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croppingApp', '0003_remove_photo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
    ]
