# Generated by Django 4.1.3 on 2022-11-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croppingApp', '0004_remove_photo_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
